from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from app.schemas.risk_evidence import RiskEvidence
from app.schemas.ai_response import AIResponse
from app.schemas.verified_response import VerificationResult, VerifiedResponse

class WorkflowState(BaseModel):
    """
    Complete state representation for the LangGraph AI workflow.
    """
    # Request Metadata
    request_id: str = Field(..., description="Unique identifier for the request.")
    identity_id: str = Field(..., description="The identity ARN or UUID being investigated.")
    workspace_id: str = Field(..., description="The workspace ID context.")
    
    # Execution Metadata
    node_history: List[str] = Field(default_factory=list, description="List of nodes visited during execution.")
    retry_count: int = Field(default=0, description="Number of retries attempted in the current workflow loop.")
    start_time: Optional[float] = Field(None, description="Workflow start timestamp.")
    
    # Workflow Data
    evidence: Optional[RiskEvidence] = Field(None, description="Evidence collected for the investigation.")
    ai_draft: Optional[AIResponse] = Field(None, description="Draft response generated by the AI analyst.")
    
    # Verification & Explainability
    extracted_claims: List[str] = Field(default_factory=list, description="Factual claims extracted from the AI draft.")
    verification_results: List[VerificationResult] = Field(default_factory=list, description="Results of the verification process.")
    confidence_score: float = Field(default=0.0, description="Calculated confidence score based on verification.")
    citations: List[Dict[str, Any]] = Field(default_factory=list, description="List of citations and references to evidence.")
    
    # Final Output
    final_response: Optional[VerifiedResponse] = Field(None, description="The final, verified response.")
    error_message: Optional[str] = Field(None, description="Any unrecoverable error encountered.")
