"""Add ReportHistory

Revision ID: 3ec7378a997d
Revises: 919a8ef47f8c
Create Date: 2026-07-03 10:42:01.640673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ec7378a997d'
down_revision: Union[str, Sequence[str], None] = '919a8ef47f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration_ms', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_history_report_id_timestamp', 'report_history', ['report_id', 'timestamp'], unique=False)
    op.add_column('reports', sa.Column('csv_url', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('report_size_bytes', sa.String(length=50), nullable=True))
    op.add_column('reports', sa.Column('version_number', sa.String(length=20), nullable=True))
    op.add_column('reports', sa.Column('generator_version', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'generator_version')
    op.drop_column('reports', 'version_number')
    op.drop_column('reports', 'report_size_bytes')
    op.drop_column('reports', 'csv_url')
    op.drop_index('ix_report_history_report_id_timestamp', table_name='report_history')
    op.drop_table('report_history')
    # ### end Alembic commands ###
