"""enterprise_audit_schema

Revision ID: 651dd7f0e3d5
Revises: 9ea31a8eeb05
Create Date: 2026-07-03 14:33:14.895990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '651dd7f0e3d5'
down_revision: Union[str, Sequence[str], None] = '9ea31a8eeb05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('event_id', sa.String(length=255), nullable=False))
    op.add_column('audit_logs', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False))
    op.add_column('audit_logs', sa.Column('actor_type', sa.String(length=50), nullable=False))
    op.add_column('audit_logs', sa.Column('module', sa.String(length=100), nullable=False))
    op.add_column('audit_logs', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('audit_logs', sa.Column('resource_type', sa.String(length=100), nullable=False))
    op.add_column('audit_logs', sa.Column('resource_id', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('correlation_id', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('parent_event_id', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('root_event_id', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_audit_logs_workspace_id_category'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_workspace_id_created_at'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_category'), 'audit_logs', ['category'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_id'), 'audit_logs', ['event_id'], unique=True)
    op.create_index(op.f('ix_audit_logs_severity'), 'audit_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_logs_workspace_category', 'audit_logs', ['workspace_id', 'category'], unique=False)
    op.create_index('ix_audit_logs_workspace_timestamp', 'audit_logs', ['workspace_id', 'timestamp'], unique=False)
    op.drop_column('audit_logs', 'target_resource')
    op.drop_column('audit_logs', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('target_resource', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index('ix_audit_logs_workspace_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_workspace_category', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_severity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_category'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_workspace_id_created_at'), 'audit_logs', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id_category'), 'audit_logs', ['workspace_id', 'category'], unique=False)
    op.drop_column('audit_logs', 'duration_ms')
    op.drop_column('audit_logs', 'root_event_id')
    op.drop_column('audit_logs', 'parent_event_id')
    op.drop_column('audit_logs', 'correlation_id')
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'resource_type')
    op.drop_column('audit_logs', 'status')
    op.drop_column('audit_logs', 'module')
    op.drop_column('audit_logs', 'actor_type')
    op.drop_column('audit_logs', 'timestamp')
    op.drop_column('audit_logs', 'event_id')
    # ### end Alembic commands ###
