"""initial_schema

Revision ID: 759ce696f877
Revises: 
Create Date: 2026-06-24 13:14:43.706197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '759ce696f877'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('event_source', sa.String(length=255), nullable=False),
    sa.Column('aws_region', sa.String(length=50), nullable=False),
    sa.Column('source_ip', sa.String(length=50), nullable=True),
    sa.Column('identity_arn', sa.String(length=512), nullable=False),
    sa.Column('resource_arn', sa.String(length=512), nullable=True),
    sa.Column('account_id', sa.String(length=12), nullable=False),
    sa.Column('raw_event_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_access_log_time_arn', 'access_logs', ['event_time', 'identity_arn'], unique=False)
    op.create_index(op.f('ix_access_logs_event_id'), 'access_logs', ['event_id'], unique=True)
    op.create_index(op.f('ix_access_logs_event_name'), 'access_logs', ['event_name'], unique=False)
    op.create_index(op.f('ix_access_logs_event_source'), 'access_logs', ['event_source'], unique=False)
    op.create_index(op.f('ix_access_logs_event_time'), 'access_logs', ['event_time'], unique=False)
    op.create_index(op.f('ix_access_logs_identity_arn'), 'access_logs', ['identity_arn'], unique=False)
    op.create_index(op.f('ix_access_logs_resource_arn'), 'access_logs', ['resource_arn'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('s3_bucket_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('events_processed', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name='status_check'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('machine_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('arn', sa.String(length=512), nullable=False),
    sa.Column('identity_type', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=12), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_events', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("identity_type IN ('AssumedRole', 'AWSService', 'IAMUser')", name='identity_type_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_identities_account_id'), 'machine_identities', ['account_id'], unique=False)
    op.create_index(op.f('ix_machine_identities_arn'), 'machine_identities', ['arn'], unique=True)
    op.create_table('risk_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('finding_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('Low', 'Medium', 'High', 'Critical')", name='finding_severity_check'),
    sa.ForeignKeyConstraint(['identity_id'], ['machine_identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_findings_finding_type'), 'risk_findings', ['finding_type'], unique=False)
    op.create_index(op.f('ix_risk_findings_identity_id'), 'risk_findings', ['identity_id'], unique=False)
    op.create_index(op.f('ix_risk_findings_severity'), 'risk_findings', ['severity'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('reasons', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('Low', 'Medium', 'High', 'Critical')", name='severity_check'),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='score_range_check'),
    sa.ForeignKeyConstraint(['identity_id'], ['machine_identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_identity_id'), 'risk_scores', ['identity_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_severity'), 'risk_scores', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_scores_severity'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_identity_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_risk_findings_severity'), table_name='risk_findings')
    op.drop_index(op.f('ix_risk_findings_identity_id'), table_name='risk_findings')
    op.drop_index(op.f('ix_risk_findings_finding_type'), table_name='risk_findings')
    op.drop_table('risk_findings')
    op.drop_index(op.f('ix_machine_identities_arn'), table_name='machine_identities')
    op.drop_index(op.f('ix_machine_identities_account_id'), table_name='machine_identities')
    op.drop_table('machine_identities')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_access_logs_resource_arn'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_identity_arn'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_event_time'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_event_source'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_event_name'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_event_id'), table_name='access_logs')
    op.drop_index('idx_access_log_time_arn', table_name='access_logs')
    op.drop_table('access_logs')
    # ### end Alembic commands ###
