"""Add report history error message and stage

Revision ID: 9ea31a8eeb05
Revises: 3ec7378a997d
Create Date: 2026-07-03 11:27:23.616036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea31a8eeb05'
down_revision: Union[str, Sequence[str], None] = '3ec7378a997d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_history', sa.Column('stage', sa.String(length=50), nullable=True))
    op.add_column('report_history', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_history', 'error_message')
    op.drop_column('report_history', 'stage')
    # ### end Alembic commands ###
